######### Configure these for each git tag release #########
git_tag:
  - "v12.9.1"
bindings_version:
  - "12.9.1"
core_version:
  - "0.3.1"
build_bindings:
  - True
build_core:
  - False
############################################################

# libcufile only exists on ARM for CUDA 12.2+. We split into two ARM packages
# with/without libcufile support.
cufile_supported:
  - True
  - False  # [aarch64]
