######### Configure these for each git tag release #########
git_tag:
  - "v13.0.1"
bindings_version:
  - "13.0.1"
core_version:
  - "0.3.2"
build_bindings:
  - True
build_core:
  - False
############################################################
python:
  - 3.9.* *_cpython
  - 3.10.* *_cpython
  - 3.11.* *_cpython
  - 3.12.* *_cpython
  - 3.13.* *_cp313
  - 3.13.* *_cp313t
  - 3.14.* *_cp314
  - 3.14.* *_cp314t
is_python_min:
  - True
  - False
  - False
  - False
  - False
  - False
  - False
  - False
python_min:
  - "3.9"

