######### Configure these for each git tag release #########
git_tag:
  - "cuda-core-v0.3.2"
bindings_version:
  - "13.0.0"
core_version:
  - "0.3.2"
build_bindings:
  - False
build_core:
  - True
############################################################
