python:
  - 3.9.* *_cpython
  - 3.10.* *_cpython
  - 3.11.* *_cpython
  - 3.12.* *_cpython
  - 3.13.* *_cp313
  - 3.14.* *_cp314
  - 3.14.* *_cp314t
is_python_min:
  - True
  - False
  - False
  - False
  - False
  - False
  - False
is_freethreading:
  - False
  - False
  - False
  - False
  - False
  - False
  - True
is_abi3:
  - False
  - False
  - False
  - False
  - False
  - False
  - False
python_min:
  - "3.9"
