######### Configure these for each git tag release #########
git_tag:
  - "v13.0.0"
bindings_version:
  - "13.0.0"
core_version:
  - "0.3.1"
build_bindings:
  - True
build_core:
  - False
############################################################
