######### Configure these for each git tag release #########
git_tag:
  - "v12.9.3"
bindings_version:
  - "12.9.3"
core_version:
  - "0.3.1"
build_bindings:
  - True
build_core:
  - False
############################################################

# libcufile only exists on ARM for CUDA 12.2+. We split into two ARM packages
# with/without libcufile support.
cufile_supported:
  - True
  - False  # [aarch64]

############################################################

python:
  - 3.9.* *_cpython
  - 3.10.* *_cpython
  - 3.11.* *_cpython
  - 3.12.* *_cpython
  - 3.13.* *_cp313
  - 3.13.* *_cp313t
  - 3.14.* *_cp314
  - 3.14.* *_cp314t
is_python_min:
  - True
  - False
  - False
  - False
  - False
  - False
  - False
  - False
is_freethreading:
  - False
  - False
  - False
  - False
  - False
  - True
  - False
  - True
is_abi3:
  - False
  - False
  - False
  - False
  - False
  - False
  - False
  - False
python_min:
  - "3.9"
