######### Configure these for each git tag release #########
git_tag:
  - "v11.8.6"
bindings_version:
  - "11.8.6"
build_bindings:
  - True
############################################################
