######### Configure these for each git tag release #########
git_tag:
  - "v13.0.1"
bindings_version:
  - "13.0.1"
core_version:
  - "0.3.2"
build_bindings:
  - True
build_core:
  - False
############################################################
python_min:
  - "3.9"

