######### Configure these for each git tag release #########
git_tag:
  - "cuda-core-v0.4.0"
bindings_version:
  - "13.0.2"
core_version:
  - "0.4.0"
build_bindings:
  - False
build_core:
  - True

############################################################

# This is temporary and will go away after conda-forge/cuda-python-feedstock#145
# is resolved. Only turn this on when building cuda.core.
cuda_major_version:
  - "12"
  - "13"

############################################################

python:
  - 3.9.* *_cpython
  - 3.10.* *_cpython
  - 3.11.* *_cpython
  - 3.12.* *_cpython
  - 3.13.* *_cp313
  - 3.13.* *_cp313t
  - 3.14.* *_cp314
  - 3.14.* *_cp314t
is_python_min:
  - True
  - False
  - False
  - False
  - False
  - False
  - False
  - False
is_freethreading:
  - False
  - False
  - False
  - False
  - False
  - True
  - False
  - True
is_abi3:
  - False
  - False
  - False
  - False
  - False
  - False
  - False
  - False
python_min:
  - "3.9"
