{% set name = "cuda-python" %}
{% set version = "11.5.0" %}
{% set major_version = version.split(".")[0] %}
{% set minor_version = version.split(".")[1] %}
{% set patch_version = version.split(".")[2] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/cuda-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 50b688ef6b3ccc4e4c26d515bbf46e4411cea64f5ce20e8a67b172c30b48b86f

build:
  number: 1
  skip: true  # [py<37 or osx]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - setuptools
    - cython
    - pycparser
    - autopxd2
    - pyclibrary
    - python
    - pip
    - cudatoolkit {{ major_version ~ ".*.*" }}
  run:
    - python
    - {{ pin_compatible('cudatoolkit', min_pin='x', max_pin='x') }}
    - pywin32  # [win]
  run_constrained:
    - __glibc >=2.17  # [linux]

test:
  imports:
    - cuda
    - cuda.cuda
    - cuda.cudart

about:
  home: https://github.com/NVIDIA/cuda-python
  license: LicenseRef-NVIDIA-SOFTWARE-LICENSE
  license_file: LICENSE
  summary: 'CUDA Python Low-level Bindings'
  description: |
    CUDA Python provides a standard set of low-level interfaces,
    providing full coverage of and access to the CUDA host APIs from Python.
  doc_url: https://nvidia.github.io/cuda-python/
  dev_url: https://github.com/NVIDIA/cuda-python

extra:
  recipe-maintainers:
    - m3vaz
    - jakirkham
    - mmccarty
    - leofang
