azure:
  free_disk_space: true
bot:
  abi_migration_branches:
    - 11.8
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
os_version:
  linux_64: cos7
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
